local repo = 'https://raw.githubusercontent.com/mstudio45/LinoriaLib/main/'

local Library = loadstring(game:HttpGet(repo .. 'Library.lua'))()
local ThemeManager = loadstring(game:HttpGet(repo .. 'addons/ThemeManager.lua'))()
local SaveManager = loadstring(game:HttpGet(repo .. 'addons/SaveManager.lua'))()

local Window = Library:CreateWindow({
    Title = "Classic Event | Script Complete Quest,Find Tix,Get Point [R]",
    Center = true,
    AutoShow = true,
    TabPadding = 5.5,
    MenuFadeTime = 0
})
local Tab = Window:AddTab("Main")
local Section = Tab:AddLeftGroupbox("Select a game")
Section:AddToggle("MyToggle"{Text="Toilet Tower Defense",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicToiletTower?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Restaurant",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicRestaurant?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Livetopia",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicLivetopia?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Gunfight",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicGunfight?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Driving Empire",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicDrivingEmpire?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Dress Tolmpress",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicDressToImpress?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Clip It",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicClipIt?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Blade Ball",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicBladeBall?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Bee Swarm",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicBeeSwarm?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Bed Wars",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicBedWars?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Arsenal",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicArsenal?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="A Dusty Trip",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicAdustyTrip?raw=true"))()
    end})
Section:AddToggle("MyToggle"{Text="Adopt Me",Default=false,Callback=function()
      loadstring(game:HttpGet("https://github.com/ToraScript/Script/blob/main/ClassicAdoptMe?raw=true"))()
    end})
Section:AddLabel("Script Made By : ToraIsMe")
